apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ml-model-deployment
spec:
  replicas: 2  # Set the desired number of replicas
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
      - name: ml-model-container
        imagePullPolicy: IfNotPresent
        image: localhost/test-model
        ports:
        - containerPort: 8080
