apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: ml-model
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will listen
      targetPort: 8080  # Port on which the Flask app is running inside the pods
  type: NodePort